### ISSUE TITLE
[infra] 開好專案

### ISSUE THREAD

**Issue by oaoxd0314** [stanely86/Movie#2]
- 使用 Next 
- Bundler : vite
- PackManager : pnpm |  npm |  yarn
- 其他你要的tool chain
  - css : tailwind / stylex / bootstrap / 
  - css pre proceser : sass 
  - 純 css : lighting css
-  typescruptt 是否要用

**Comment by stanely86** [comment]
Installed:
- **使用 Next (Prefer)** / Bundler : vite
- PackManager : npm
- css : tailwind
- typescript

--------
(預估決定時間: 4/22)
考慮使用中:
- **使用 Next (Prefer)** / Bundler : vite
- css : stylex /
- css pre proceser : sass

**Comment by oaoxd0314** [comment]
我建議你可以寫成：
```markdown=
## Description
創建並決定這份專案的基礎建設，最後將這些項目實作出來：
- FrameWork : Next
- Bundler : Vite
- 是否套用 Typescript 提升 DX: 是
- ... etc
```

條列這些你要實作的項目，有助於幫助你在過程中釐清你想實作的目標，並在心中有清楚的 roadmap，這樣可以大大加速你的開發流程


## Note 
用一些簡單分類，把這些資訊整理好，例如：

```markdown=
<!-- Issue Template -->
## Description
<!-- 先描述 你想達成的事 / 發現的問題 -->

<!-- [Optional] 再描述目前的情況，改動之後會怎麼樣達成目標 -->

<!-- 描述你該怎麼實做，簡短條列步驟 -->

<!-- 最後描述你預期會完成目標後，應該呈現的狀態 / 結果 -->
```

```markdown=
<!-- PR Template -->
## Intro
<!-- 用 2~3 行簡單描述這份 PR -->

## Changes
<!-- 條列你再這份 PR 做的改動 -->
```

**Comment by stanely86** [comment]
以下部分我不太懂，若完成原進度有時間我會回來了解:



## Intro


## Changes
