### ISSUE TITLE
[Tech] survey 怎麼串第三方登入

### ISSUE THREAD

**Issue by oaoxd0314** [stanely86/Movie#3]
- [ ] 以及我們要串哪一些第三方登入
- [ ] https://console.firebase.google.com/

**Comment by stanely86** [comment]
- 第三方登入使用: FB, Google, Twitter

---
(預計確認時間 : 4/23)
- 確認可否使用IMDB, 爛番茄 API  
- 搜尋API wtih type hint

**Comment by oaoxd0314** [comment]
使用[type hint API](https://jsonplaceholder.typicode.com/) 這是什麼 ，你的主要目的是要達成什麼

網址好像貼錯了

如果你是指驗證 api resonse 的話 你可以先查查看 [zod](https://zod.dev/) 

不過這一樣是從 70 -> 80 的作用，所以還是建議，先想辦法達到 60 分之後，還有餘裕我們再做這些

**Comment by stanely86** [comment]
使用[type hint API](https://jsonplaceholder.typicode.com/) 主要是用來完成搜尋建議功能
![Screenshot 2024-04-23 220440](https://github.com/stanely86/Movie/assets/58258424/e1f63603-5ef6-480e-acbf-2bd19a2cbf7c)
