### ISSUE TITLE
預估周進度 Week 4/22 ~ 4/28

### ISSUE THREAD

**Issue by stanely86** [stanely86/Movie#4]
- 熟悉stylex ，使用建立首頁 
- 找到且了解如何使用 IMDB Search API
- 使用API 建立Search hint Drop down
- 確認如何使用Firbase API For Auth

**Comment by stanely86** [comment]
本週預計實作 :
- #1 ( 1天 ) 熟悉stylex ，使用建立首頁
- #2 ( 1天 ) 找到且了解如何使用 IMDB Search API
- #3 ( 1天 ) 使用API 建立Search hint Drop down
- #4 ( 1天 )確認如何使用Firbase API For Auth

**Comment by oaoxd0314** [comment]
> 前陣子我在忙我的績效評估，稍微比較忙一點，今天結束之後可以正常幫你看了

先稍微跟你說一下，預計實做 === 一定會完成，雖然我們現在不是在工作，不用這麼嚴格，但說起來「預計實作」這個意思就是這樣

否則可能會在你下次的 squad sync up 時，如果沒有講出好的理由，就很容易損失其他人的信賴( 這很嚴重 )。

所以相反的來說，你預計實做的項目可以是你 100% 完成的了得項目， 例如你預計有 80% 的能量，但你可以只抓 60% 的事情來做，這是完全可以的。

**Comment by stanely86** [comment]
Ok, 上面4張單沒完成主要是各Task都比預期想的要難，實作起來蠻大幅超出原預估時間。

現在我在各張單有細節列出欲達成的Fetuare，還有預計完成所需時間。 P.S. 問一下，在專案中，每次規劃完成項目時，可否多列出的實作項目但下一階段才實作，如果當階段就表示預計是下階段的實作。
