### ISSUE TITLE
( 1天 ) 熟悉stylex ，使用建立首頁

### ISSUE THREAD

**Issue by stanely86** [stanely86/Movie#5]
## 想達成的事 / 發現的問題
使用過Stylex編輯CSS。因為沒有使用過，想先嘗試建一個頁面了解語法。

## [Optional] 目前的情況，改動之後會怎麼樣達成目標
目前只知道可用來實作CSS，經此實作後能了解如何撰寫。

## 該怎麼實做，簡短條列步驟 
1.查資料、爬文
2.建立測試專案
3.編修過去的Todolist進行練習。

## 預期會完成目標後，應該呈現的狀態 / 結果
知悉在Stylex如何寫在專案，可應用CSS基礎在專案。

**Comment by oaoxd0314** [comment]
有相對應的結果更新嗎，記得更新上來，其他空白的我就不重複問了，但你要記得更新。

---
提供一個做法給你，不管有沒有達成你想完成的目標，都可以隨時記錄目前的情況上來

就像把這裡當作自己的 work log ，如果團隊內其他人有看到，就會更願意去協助你( 資訊更明瞭 )

**Comment by stanely86** [comment]
## 當前進度
成功安裝並了解如何使用Stylex。尚未建立首頁。嘗試使用StyleX在上一個TodoList專案，但無法成功安裝。

## 待完成項目
-建立首頁
