### ISSUE TITLE
[Planning] 2024 05 04 

### ISSUE THREAD

**Issue by oaoxd0314** [stanely86/Movie#9]
## Sync
- #6 實作狀況不如預期，下週繼續實作
  - [Optional] 找到更能夠容易使用的 Movie API 

## Plan 
- #6 預計實作到:
  - 按照日期抓取電影內容，大致結果如下圖
    - ”按照日期 -> 發行時間兩個月內的電影“
  <img width="1118" alt="image" src="https://github.com/stanely86/Movie/assets/48309943/21091936-b13b-4d6c-ba62-f868b2a84141">
  - 將目前的基底 Next 專案上傳，才能方便 @oaoxd0314 實作
    - 專案管理的部分設定

## Note
- 下次 Planning 時間改為 5/24 8:00 pm

**Comment by stanely86** [comment]
## Completed
- 在NextJS框架下，可使用Search 抓取10筆演員資訊，並顯示出來。
![Screenshot 2024-05-04 233659](https://github.com/stanely86/Movie/assets/58258424/73e4f4fe-ed36-46ed-9631-70e224931e1b)

##Problem
- 部分結果無圖片，在思考如何處理
![Screenshot 2024-05-04 233659](https://github.com/stanely86/Movie/assets/58258424/ae2778c3-ee07-43eb-920b-7f10cb8626ab)


## Pending Tasks
- 解構Movie的 dataStructure，已建立搜尋API抓取路徑
- 建立 dropdown 功能進行 "movie" "star" 的搜尋邏輯分支
